# Generated by Django 5.0.6 on 2024-07-09 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newscategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('activity', models.CharField(choices=[('welder', 'Сварщик'), ('firefighter', 'Пожарный'), ('mechanic', 'Мастер по ремонту и обслуживанию автомобилей'), ('computer_systems', 'Компьютерные системы и комплексы'), ('information_systems', 'Информационные системы и программирование'), ('electrical_equipment', 'Эксплуатация и обслуживание электрического и электромеханического оборудования (по отраслям)'), ('engineering', 'Технология машиностроения'), ('maintenance', 'Техническое обслуживание и ремонт двигателей, систем и агрегатов автомобилей'), ('accounting', 'Экономика и бухгалтерский учет (по отраслям)'), ('law_enforcement', 'Правоохранительная деятельность'), ('jurisprudence', 'Юриспруденция'), ('design', 'Дизайн (по отраслям)')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
